<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BrandsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {


        $brands = [
            "22 Miles, Inc",
            "3Dconnexion",
            "3M",
            "42Gears Mobility Systems Pvt Ltd",
            "AAEON Electronics Inc",
            "Aaxa Technologies, Inc",
            "Absolute Software Corp",
            "Accell Corporation",
            "Acco Brands Corporation",
            "ACCUTIME WATCH CORPORATION",
            "Acer, Inc",
            "Acronis, Inc",
            "Acunetix",
            "Adaptec, Inc",
            "A-Data Technology Co., Ltd",
            "Addon",
            "Adesso, Inc",
            "Adobe Inc.",
            "Advanced Industrial Computer, Inc",
            "Advanced Micro Devices, Inc",
            "Advantech Co., Ltd",
            "Advent",
            "Ag Antenna Group, LLC",
            "Ag Neovo Technology Corporation",
            "Agi",
            "Agora Leather Products",
            "Agosto Inc",
            "Aidata Corp.",
            "Airtame",
            "Badge Plus Inc.",
            "Bakker Elkhuizen",
            "Barco",
            "Battery Technology, Inc",
            "Be Quiet!",
            "Beam Mobile",
            "Bec",
            "Belkin International, Inc",
            "Bematech",
            "Benq Corporation",
            "Beyondtrust Software, Inc",
            "Bitdefender",
            "Bitech Group",
            "Bittitan",
            "Bixolon America, Inc",
            "Black Box Corporation",
            "BLACK PEARL MAIL",
            "Blackberry",
            "Blancco Technology Group",
            "Blu",
            "Blu Products",
            "Blue Jeans Network, Inc",
            "Bluerover Inc.",
            "Bluestar Communications",
            "BLUETTI",
            "C2g",
            "Ca Technologies",
            "Cable Matters Inc.",
            "Callture Communications Inc.",
            "Canon, Inc",
            "Capital Networks Limited",
            "Cardinal Scale Manufacturing Company",
            "Cardmark",
            "Cas Corp",
            "Case Logic, Inc",
            "Casio Computer Co., Ltd",
            "Centon Electronics",
            "Chargifi Ltd",
            "Check Point Software Technologies, Ltd",
            "Chenbro Micom Co., Ltd",
            "Cherry Americas",
            "Chief Manufacturing",
            "Ciena Corporation",
            "CIMCON Lighting",
            "Cipherlab Co., Ltd",
            "Cirque Corporation",
            "Cisco Systems, Inc",
            "Citizen Micro Humantech",
            "Citrix Systems, Inc",
            "Claris International Inc",
            "Lite Screen Company",
            "Datacard Group",
            "Datacolor",
            "Datalocker",
            "Datalogic S.P.A",
            "Datamation Systems, Inc",
            "Datamax Bar Code Products Corporation",
            "Datamax-O'Neil",
            "DataVisual",
            "Datex",
            "Deep Instinct (Usa)",
            "Deepcool Industries Co., Ltd",
            "Dell Technologies",
            "Denso Td Scan, Inc",
            "Digi International",
            "Digi Op",
            "Digipos Systems",
            "Digium, Inc",
            "Distinow",
            "Diversified Labeling Solutions, Inc.",
            "D-Link Systems, Inc",
            "Docusign, Inc.",
            "DPI Inc",
            "Dpr Llc.",
            "DPVR",
            "E.C.I.Networks",
            "Eastman Kodak Company",
            "Eaton Corporation",
            "Ecoprintq Inc.",
            "ECOVACS Inc",
            "Edge-Core Networks Corporation",
            "Edifier International Limited",
            "Edimax Technology",
            "EIZO",
            "Ej-Technologies, Gmbh",
            "Ekahau, Inc",
            "Elite Screens, Inc",
            "Elitegroup Computer Systems",
            "Elmo Company, Ltd",
            "Elo Touch Solutions, Inc",
            "Elsa Technology, Inc",
            "Elunevision",
            "Embrava",
            "eMeet",
            "E-Nabler Corporation",
            "Engenius Technologies, Inc",
            "Ens Group",
            "Epadlink",
            "Epos, Ltd",
            "Epson Corporation",
            "F5 Networks",
            "Fabcon",
            "Fast Lane",
            "Feitian Technologies Us, Inc.",
            "Fellowes, Inc.",
            "Finisar Corporation",
            "Firich Enterprises Co",
            "Fixmestick",
            "Flextronics International, Ltd.",
            "Flir Security",
            "Fluke Networks",
            "FONEX Data Systems, Inc",
            "Forcepoint LLC.",
            "Fortinet, Inc",
            "Foxit Corporation",
            "Fractal Design",
            "Freeform",
            "Freewave Technologies, Inc.",
            "Fsp Group Usa Corp",
            "Fuji Photo Film Co. Ltd",
            "Fujitsu",
            "Funai Electric Co., Ltd",
            "Futurenova",
            "Galaxy Securitiy",
            "Gamber-Johnson, LLC",
            "Gammatech Computer Corp",
            "Garmin, Ltd",
            "Garner Products",
            "Geminicomputersinc.Com",
            "General Dynamics Itronix Corporation",
            "Generic",
            "Gentek Marketing, Inc",
            "Geovision, Inc",
            "Getac, Inc",
            "GETT",
            "Gigabyte Technology, Inc",
            "Gigamon Inc.",
            "GIGE Computer Shop.",
            "Global Knowledge Training, LLC",
            "Global Technology Systems, Inc",
            "Goal Zero",
            "Goldseal",
            "Google, Inc",
            "Gooxi",
            "Grandstream Networks, Inc",
            "GTR Simulator",
            "Gunnar Optiks, LLC",
            "Gvision, Inc",
            "Hamilton Buhl",
            "Harvard Battery",
            "Hasbro",
            "Hasselblad",
            "Havis, Inc",
            "Heckler Design",
            "Helios Retail Consulting Ltd.",
            "Hellosign",
            "Hewlett Packard Enterprise",
            "Hgst, A Western Digital Company",
            "Hid Global Corporation",
            "Highfive",
            "Highpoint Technologies, Inc",
            "Hikvision",
            "Hiperwall, Inc",
            "Hippus, N.V",
            "Hiro, Inc",
            "Hisense Company Limited",
            "Honeywell International, Inc",
            "Hovercam",
            "HP Inc.",
            "Htc",
            "Huawei Technologies Co., Ltd",
            "Human Active Technology, LLC",
            "Humanscale Corporation",
            "IAconnects Technology Ltd",
            "Ibm Corporation",
            "Iboss Cybersecurity",
            "Ibuypower Computer",
            "Ic Realtime Security Solutions",
            "Icy Dock",
            "Id Innovations",
            "Id Tech",
            "Igel Technology",
            "Iimak",
            "Ikey, Ltd",
            "Im Outlet - Comsale",
            "Imo Precision Controls Ltd",
            "Imperva, Inc",
            "Impinj, Inc",
            "Imprivata, Inc",
            "In Win Development, Inc",
            "Industrial Electronic Engineers, Inc",
            "Industry Weapon",
            "Infinite Peripherals",
            "Ingenico",
            "Ingram Micro, Inc",
            "Inland Products, Inc",
            "Innovative Office Products",
            "Innowi",
            "Jabra",
            "Jam",
            "Janam Technologies, LLC",
            "Jar Systems, LLC",
            "Jarden Corporation",
            "Jetway Computer Corporation",
            "Jewell Instruments",
            "Jolly Technologies",
            "Juniper Systems, Inc.",
            "Kandao",
            "Kanguru Solutions",
            "Kensington Computer Products Group",
            "Key Source International, Inc",
            "Keychron",
            "Keyovation, LLC",
            "Kinesis Corporation",
            "Kingston Technology Company",
            "Kioxia",
            "Koamtac, Inc",
            "Konica Minolta",
            "KONTAKT",
            "Kore Design Llc.",
            "Koss Corporation",
            "Kramer Electronics Ltd",
            "Kyocera Corporation",
            "Label Accessories Inc",
            "Labelmate",
            "Lacie",
            "Lantronix, Inc",
            "Lapcabby",
            "Laplink Software, Inc",
            "LaserPecker",
            "Lavu",
            "Layer8 Training, Inc.",
            "Layered Solutions Inc.",
            "Leaf",
            "LEAF LEARNING",
            "LECTRON",
            "Legrand Group",
            "Lenovo Group Limited",
            "Lepa Technology Corporation",
            "Lexar, Inc",
            "Lexmark International, Inc",
            "Leyard",
            "Lg Electronics",
            "Lian Li Industrial Co., Ltd",
            "LifeMed ID",
            "Lifesize Communications, Inc",
            "Lightspeed Systems",
            "Linksys",
            "M5 TECHNOLOGIES",
            "Mad Catz, Inc",
            "Magix Ag",
            "Magtek, Inc",
            "Makerbot Industries, Llc.",
            "Man &amp; Machine, Inc",
            "MANDIANT",
            "Manhattan",
            "Matias Corporation",
            "Matrox",
            "Maxell",
            "Mcafee, Inc",
            "Mediasonic Enterprises",
            "meldCX",
            "Meridian Kiosks, LLC",
            "Microchip Technology Inc.",
            "Micron Technology, Inc",
            "Microsoft Corporation",
            "Microspareparts",
            "Micro-Star International Co., Ltd",
            "Microtouch",
            "Middle Atlantic Products, Inc",
            "Milestone Systems",
            "Mimecast Services Limited.",
            "Mimo Monitors, Inc",
            "N-Able Technologies, Inc",
            "Nanolumens",
            "National Products, Inc",
            "National Service Center",
            "Navori, Inc.",
            "Ncipher Security",
            "Nclose, Inc",
            "Ncomputing Co. Ltd",
            "Ncp Network Communications Products Engineering",
            "Ncr Corporation",
            "Nec Display Solutions",
            "Nest Labs, Inc",
            "Netally",
            "Netgear, Inc",
            "Netlist",
            "Netscout Systems, Inc",
            "Netvox",
            "Newcastle",
            "Newell Brands",
            "Newline Products, Inc",
            "Nexenta Systems",
            "Nexsan Technologies, Inc",
            "Nginx Inc",
            "Niceware International, LLC",
            "Nikon Corporation",
            "Offsitedatasync",
            "Oki Data",
            "Okta, Inc.",
            "Omnicharge",
            "Open Text Corporation",
            "Opengear",
            "Opswat, Inc.",
            "Opticon Sensors Europe",
            "Optoma Technology",
            "Other World Computing",
            "Otterbox",
            "Overland Tandberg",
            "Owl Labs",
            "PacTech",
            "Palmer",
            "Palo Alto Networks",
            "Panasonic",
            "Panduit Corp",
            "Panorama Antennas Ltd",
            "Para Systems, Inc",
            "Parsec Technologies",
            "Partner Tech Usa",
            "Patriot Memory, LLC",
            "Pax",
            "Pcamerica",
            "Peerless Industries, Inc",
            "Performance Designed Products, LLC",
            "Perle Systems, Inc",
            "Petawise",
            "Pgytech",
            "Phanteks Company",
            "Philips Electronics",
            "Phishme Privacy Policy",
            "PHISON",
            "Phoenics Electronics",
            "Pioneer Pos, Inc",
            "Pi-Top",
            "Pivot3, Inc",
            "Qnap Systems",
            "Quanta Computer, Lnc",
            "Quantum Corporation",
            "Quest",
            "Quetzal",
            "Rack Solutions",
            "Rackmount.It",
            "Radware Ltd",
            "Rain Design, Inc",
            "Raritan Computer",
            "RayNeo",
            "Rbh Access Technologies, Inc",
            "Realwear, Inc",
            "Red Hat, Inc",
            "Redbeam, Inc",
            "Retrospect, Inc",
            "Rf Ideas, Inc",
            "Rgb Spectrum",
            "R-Go Tools",
            "Rhombus Systems, Inc",
            "Ricoh Company, Ltd",
            "Ring",
            "Riso",
            "Robert Bosch Gmbh",
            "Rocstor",
            "Rogers Communications, Inc",
            "Roku, Inc",
            "Roland Corporation",
            "Roots Canada Ltd",
            "Rsa Security, Inc",
            "Safco Products",
            "Salamander Designs",
            "Samson",
            "Samsung",
            "Sandisk Corporation",
            "Sandvine",
            "Sangoma Technologies Corporation",
            "Sapphire, Inc",
            "Satechi",
            "Sato Corporation",
            "Scala, Inc",
            "Scale Computing",
            "Schneider Electric Sa",
            "Scosche Industries",
            "ScreenBeam Inc.",
            "ScreenCloud",
            "Sea Sonic Electronics Co., Ltd",
            "Seagate Technology",
            "Seagull Scientific, Inc",
            "Seal Shield Corporation",
            "SecuGen Corporation",
            "Secure-It, Inc",
            "Seiko Instruments Usa, Inc",
            "Sencor",
            "Seneca Data Distributors, Inc",
            "Tangent, Inc",
            "Taoglas",
            "Targus Group International",
            "Tatung Co",
            "Taylor Precision Products, Inc",
            "Team Group Incorporated",
            "Team Nisca",
            "Technology Solutions Uk Ltd",
            "Teklynx International",
            "TEKTELIC Communications Inc.",
            "Telus Communications Company",
            "Temperature@Lert",
            "Terranova",
            "Test Vendor",
            "Tg3 Electronics",
            "Thales",
            "The Bosch Group",
            "The Gillette Company",
            "The Joy Factory",
            "The Sage Group Plc",
            "The Siemon Company",
            "Thermaltake Technology Co., Ltd",
            "Thermamark",
            "Thinkparq",
            "Tightrope Media Systems Inc",
            "U.S. Robotics",
            "Ubiquiti Inc.",
            "Ucp Inc",
            "UCView Digital Signage",
            "Uipath",
            "Ultima Cosa",
            "Ultra Electronics Card Systems",
            "Umango LLC",
            "Uncanny Vision",
            "Uniform Industrial Corporation",
            "Unique Secure Ltd.",
            "Unitech Electronics Co., Ltd",
            "UNITY TECHNOLOGIES SF",
            "Unytouch Manufacturing",
            "Vaddio",
            "Valcom, Inc",
            "Vantec Thermal Technologies",
            "Vectra AI",
            "Veea Inc.",
            "Veeam Software",
            "Velocloud Networks, Inc.",
            "Ventev Innovations",
            "Verbatim America, LLC",
            "Verifone, Inc",
            "Veritas Technologies LLC",
            "Vertiv Co",
            "Viavi Solutions Inc",
            "Vidizmo",
            "ViewSonic Corporation",
            "Viking Enterprise Solutions",
            "Vipre",
            "Visiontek Products, LLC",
            "Vivotek, Inc",
            "Viziflex Seels, Inc",
            "Vizta",
            "VMware, Inc.",
            "Vonnic, Inc",
            "Wacom Technology Co",
            "Wasabi Technologies, Inc",
            "Wasp Barcode Technologies",
            "WasteHero ApS",
            "Watchguard Technologies, Inc",
            "Wausau Paper Corp.",
            "Wavelink Corporation",
            "Wbm International",
            "Weightronix Controls",
            "Western Digital Corporation",
            "Wilson Electronics",
            "Wireless Links",
            "Withings",
            "WiZconnected Co., Ltd",
            "Xerox Corporation",
            "XGIMI",
            "Xilinx Inc.",
            "Xinuos Inc",
            "Xpress Systems",
            "Xtreme Performance Gear",
            "Yale",
            "Yamaha Corporation",
            "Yealink Network Technology Co., Ltd",
            "YUBICO",
            "Zagg, Inc",
            "Zba, Inc",
            "Zebra Technologies Corporation",
            "Zerto",
            "Zoom Telephonics, Inc",
            "Zoom Video Conferencing",
            "Zotac International",
            "Zyxel Communications Corp."
        ];


        foreach ($brands as $brand) {
            DB::table('brands')->insert([
                'name' => $brand,
                'slug' => \Str::slug($brand),
                'logo' => '', // Adjust as needed for logo path
                'is_featured' => false, // Set to true if needed
                'status' => true, // Set to false if needed

            ]);
        }
    }
}
